### ISSUE TITLE
Issue on Placing a Globe. "NetworkDispatcher exception"

### ISSUE THREAD

**Issue by Gamersven** [iChun/Globe#2]
Hello IChun, 

i was testing a self created Modpack and in it was Globe.
So i tested some things.

This error occured when i was placing a globe on the globestand. In Inventory it was fine.
The Globe Contained another Globe on a stand, blocks and myself(flying).
It is not an Optifine issue because i tested it without it. 
Forge Version 14.23.2.2654

weirdly enough, i cant upload the log file to GitHub "Something went really wrong, and we can’t process that file." and it is too big to fit into pastebin so i put a link to my GDrive: https://drive.google.com/open?id=1CwRA_VgDv5XTrXI7re059ei0XDRzjucG

(NOT A COMPLAINT: Globe Items dont render in the Inventory with Optifine, but in World it looks Fantasic 😄)

**Comment by iChun** [comment]
The NBT tag is too big. I will have to work around it in the future.

[21:26:03] [Netty Local Client IO #0/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28)
~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142)
~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:534)
~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245)
[gw$4.class:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]

**Comment by Gamersven** [comment]
Thank you for the early reply I appreciate it :)
